### ISSUE TITLE
Raise error or return False when validate

### ISSUE THREAD

**Issue by miluChen** [leocalm/avro_validator#12]
https://github.com/leocalm/avro_validator/blob/ef7fd09da10dd4e283555b326884869b5305f0b7/avro_validator/avro_types.py#L543
For now, the above `validate` function raise exception upon invalid data and returns `True` otherwise. Would it be better to have another optional parameter indicating whether to raise the exception? Something like below:
```python
def validate(self, value: Any, raise_errors=True) -> bool:
```
Without this, users will have to do below to get around it if they only care about whether the data is valid (not caring about what exactly error it is). And I think this scenario is quite common, e.g. users may only want to process some data that matches the schema and simply discard other data.
```python
valid = False
try:
    valid = schema.validate(data)
except ValueError:
    pass
```

**Comment by leocalm** [comment]
I've added a `schema.validate` method, check here: https://github.com/leocalm/avro_validator/pull/14

Version 1.0.7 includes the `validate` method.
