### ISSUE TITLE
Validator doesn't understand recursive schemas

### ISSUE THREAD

**Issue by fjahoda** [leocalm/avro_validator#13]
ValueError: The type [Actor] is not recognized by Avro

```py
import json
from avro_validator.schema import Schema

SCHEMA = {
    "name": "Actor",
    "type": "record",
    "fields": [
        {
            "name": "actedBy",
            "type": ["null", "Actor"],
        }
    ]
}

Schema(json.dumps(SCHEMA)).parse()
```

**Comment by leocalm** [comment]
Hey, thanks for the heads-up, created a new version that supports this: https://github.com/leocalm/avro_validator/releases/tag/1.0.9

Let me know if you have any more improvement ideas.

**Comment by fjahoda** [comment]
Thank you for implementing this. I read through the code and it wasn't the small change.

Unfortunately we did the validation ourselves (private project), because we wanted to generate message builders and when you have them it also makes sense to do validation directly inside them. Still I think this change makes your library usable in wider context and I can recommend it.
