### ISSUE TITLE
Valid data files with nullable fields not correctly validated

### ISSUE THREAD

**Issue by cbcoutinho** [leocalm/avro_validator#16]
Avro records with nullable fields (based on union types) encoded as JSON
are not correctly parsed using the `avro_validator` cli. The error is
due to an inconsistency in how this tool interprets union types and how
they're encoded in JSON ([link to docs](http://avro.apache.org/docs/current/spec.html#json_encoding)).

Specifically:

> For example, the union schema ["null","string","Foo"], where Foo is a
> record name, would encode:
>
>	1. null as null;
>	2. string "a" as {"string": "a"}; and
>	3. a Foo instance as {"Foo": {...}}, where {...} indicates the JSON encoding of a Foo instance.

The following schema includes some nullable fields, which can be used to
generate some random data.

```json
{
  "type" : "record",
  "name" : "test",
  "namespace" : "com.example",
  "fields" : [ {
    "name" : "name",
    "type" : "string"
  }, {
    "name" : "null_name1",
    "type" : [ "null", "string" ]
  }, {
    "name" : "null_name2",
    "type" : [ "string", "null" ]
  }, {
    "name" : "num",
    "type" : "int"
  }, {
    "name" : "null_num1",
    "type" : [ "null", "int" ]
  }, {
    "name" : "null_num2",
    "type" : [ "int", "null" ]
  } ]
}
```

This following record fails the validation based on the above schema:

```json
{
  "name": "snhepdirqromqkgllhgljumtuj",
  "null_name1": null,
  "null_name2": null,
  "num": 186374858,
  "null_num1": {
    "int": -1433093325
  },
  "null_num2": {
    "int": -1728851584
  }
}
```

```shell
$ avro_validator test.avsc test.json
Error validating value for field [null_num1]: The value [{'int': -1433093325}] is not from one of the following types: [[NullType, IntType]]
```

**Comment by manmat** [comment]
Your input data doesn't match the schema. `null_num1` is infact not an int. It's a dictionary with a field with key `int` and value `-1433093325`. This is expected to not be validated.

**Comment by nrao57** [comment]
> Your input data doesn't match the schema. `null_num1` is infact not an int. It's a dictionary with a field with key `int` and value `-1433093325`. This is expected to not be validated.

This is not correct. When encoding data in JSON with avro, and the field is nullable, YOU MUST include the type
[Avro Specification](https://avro.apache.org/docs/current/spec.html#json_encoding)

Since `null_num1` is a nullable `int` you must encode it in json as 
```
"null_num1": {
    "int": -1433093325
  }
```
