### ISSUE TITLE
Schema constructor fails on a long json string

### ISSUE THREAD

**Issue by yurymann** [leocalm/avro_validator#4]
I'm calling `avro_validator.schema.Schema(s)` where `s` is a json string and `len(s)==33335`. 
The constructor throws the following exception: 

> {ValueError}stat: path too long for Windows

It's probably not correct to use os.path.isfile() to distinguish between files and json strings. The simplest fix would be to wrap it in a try/catch and treat an exception as another indicator that it's not a file.

**Comment by leocalm** [comment]
Replaced `os.path.isfile` with `pathlib.Path.exists`, should be fine
