### ISSUE TITLE
Neither "null" in the union type nor default are respected

### ISSUE THREAD

**Issue by yurymann** [leocalm/avro_validator#6]
I have the following field declared in my schema, but missing in the data:

```python
    {
      "name": "myField",
      "type": [
        "null",
        {
          "type": "map",
          "values": {
            "type": "string",
            "avro.java.string": "String"
          },
          "avro.java.string": "String"
        }
      ],
      "default": null
    }
```

I would expect the schema validator to ignore it given that it both has "null" as a part of union type and as default. However, the validator throws the following error:
```
ValueError: Error parsing the field [surfaceIds]: The MapType can only contains {'values', 'type'} keys
```

**Comment by leocalm** [comment]
Your avro schema doesn't seem to be valid.

Definition of the Map type is:
```
Maps use the type name "map" and support one attribute:

values: the schema of the map's values.
Map keys are assumed to be strings.

For example, a map from string to long is declared with:

{"type": "map", "values": "long"}
```

Maybe if you changed your schema to the following it should work:
```
    {
      "name": "myField",
      "type": [
        "null",
        {
          "type": "map",
          "values": "string" 
        }
      ],
      "default": null
    }
```

This error is about the schema itself, not the data.

Also, the error does not correspond to the example provided. In the example, the field is named `myField` and in the error message the field is named `surfaceIds`

Can you provide the actual definition of the `surfaceIds` field, please?
